# Generated by Django 5.2.3 on 2025-06-19 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(choices=[('WW', 'Written Work'), ('PT', 'Performance Task'), ('QA', 'Quarterly Assessment')], max_length=2)),
                ('score', models.FloatField()),
                ('highest_possible_score', models.FloatField()),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='GradingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_work_weight', models.FloatField(default=0.4)),
                ('performance_task_weight', models.FloatField(default=0.4)),
                ('quarterly_assessment_weight', models.FloatField(default=0.2)),
                ('class_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grading_scheme', to='classroom.class')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
            options={
                'unique_together': {('student', 'class_obj')},
            },
        ),
    ]
