# Generated by Django 5.2.3 on 2025-06-21 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('classroom', '0001_initial'),
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalgrade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='quarter',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='finalgrade',
            unique_together={('student', 'class_obj', 'quarter')},
        ),
    ]
