# Generated by Django 5.2.3 on 2025-08-12 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('classroom', '0002_alter_class_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.class')),
            ],
            options={
                'unique_together': {('class_obj', 'date')},
            },
        ),
    ]
